### ISSUE TITLE
FoE: simply increasing the buffer size?

### ISSUE THREAD

**Issue by sirop** [ribalda/ethercat#10]
Hello.

We could successfully write a config file to our Copley slave with
`ethercat foe_write -p0 Ourfile.xml` .

But reading this file back  with `ethercat foe_read -p0 -o output.xml devcfg.xml` was not possible,
as first we got an error message about _rx_buffer_ being too small. Seemed reasonable as our file is about
90 KB.

So we increased the buffer size in https://github.com/ribalda/ethercat/blob/master/tool/CommandFoeRead.cpp#L117
up to 100000 bytes, this caused the following error messages in the kernel log:
````
[Tue May 11 12:00:38 2021] EtherCAT 0: Slave states on main device: PREOP.
[Tue May 11 12:01:15 2021] EtherCAT ERROR 0-main-0: Received packet number 0, expected 256.
[Tue May 11 12:01:15 2021] EtherCAT ERROR 0-main-0: Failed to handle FoE request.
[Tue May 11 12:01:59 2021] EtherCAT ERROR 0-main-0: Received packet number 0, expected 256.
[Tue May 11 12:01:59 2021] EtherCAT ERROR 0-main-0: Failed to handle FoE request.
````

So our naive approach failed.
Still: is there a quick remedy for this?

**Comment by ribalda** [comment]
Hi @sirop Please contact the oficial mailing list. This repo is just to ease packagers of ethercat not for active development.

Thanks!
