### ISSUE TITLE
error with Xenomai 3.1

### ISSUE THREAD

**Issue by ChenluLiu123** [ribalda/ethercat#5]
hello .:
when I want to install the ethercat to ubuntu 16 with kernel 4.4 and Xenomai 3.1 ,  RTDM errors. it shows that asm/xenomai/wrappers.h no such file or directory . Could you tell me how to solve this problem?

best wishes

**Comment by ribalda** [comment]
Sorry I am focus on Linux only without patches. You will receive more help on the ethercat mailing list.
