### ISSUE TITLE
r8169 device in 4.19

### ISSUE THREAD

**Issue by summerlotus513** [ribalda/ethercat#7]
r8169 device in 4.19
hello，I want to use the igh with kernel 4.19,my PHY is r8169，but the 8169's device support to 4.14.
I read the source 4.14 & 4.19,find them different。
I want to adapt the driver to 4.19 . What should I do?

**Comment by summerlotus513** [comment]
i have work it, close

**Comment by zeroxcen** [comment]
> 4.19 中的 r8169 设备 你好，我想使用 igh 的 4.19 内核，我的 PHY 是 r8169，但是 8169 的设备支持到 4.14。 我看了 4.14 和 4.19 的源代码，发现它们不一样。 我想将驱动适配到 4.19。我应该怎么做？

请问怎么解决的呢
